// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SemaforosInteligentes.Migrations
{
    [DbContext(typeof(SemaforosDbContext))]
    partial class SemaforosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SemaforosInteligentes.Models.DimCarril", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCarril")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVehiculoPermitido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimCarriles");
                });

            modelBuilder.Entity("SemaforosInteligentes.Models.DimInterseccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreInterseccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UbicacionGeografica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimIntersecciones");
                });

            modelBuilder.Entity("SemaforosInteligentes.Models.DimSemaforo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AñoInstalacion")
                        .HasColumnType("int");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimSemaforos");
                });

            modelBuilder.Entity("SemaforosInteligentes.Models.DimTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DimTiempos");
                });

            modelBuilder.Entity("SemaforosInteligentes.Models.HechoTrafico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadVehiculos")
                        .HasColumnType("int");

                    b.Property<int>("DimCarrilId")
                        .HasColumnType("int");

                    b.Property<int>("DimInterseccionId")
                        .HasColumnType("int");

                    b.Property<int>("DimSemaforoId")
                        .HasColumnType("int");

                    b.Property<int>("DimTiempoId")
                        .HasColumnType("int");

                    b.Property<string>("LuzSemaforo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TiempoEsperaSeg")
                        .HasColumnType("real");

                    b.Property<float>("VelocidadPromKmh")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DimCarrilId");

                    b.HasIndex("DimInterseccionId");

                    b.HasIndex("DimSemaforoId");

                    b.HasIndex("DimTiempoId");

                    b.ToTable("HechosTrafico");
                });

            modelBuilder.Entity("SemaforosInteligentes.Models.HechoTrafico", b =>
                {
                    b.HasOne("SemaforosInteligentes.Models.DimCarril", "DimCarril")
                        .WithMany()
                        .HasForeignKey("DimCarrilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemaforosInteligentes.Models.DimInterseccion", "DimInterseccion")
                        .WithMany()
                        .HasForeignKey("DimInterseccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemaforosInteligentes.Models.DimSemaforo", "DimSemaforo")
                        .WithMany()
                        .HasForeignKey("DimSemaforoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemaforosInteligentes.Models.DimTiempo", "DimTiempo")
                        .WithMany()
                        .HasForeignKey("DimTiempoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimCarril");

                    b.Navigation("DimInterseccion");

                    b.Navigation("DimSemaforo");

                    b.Navigation("DimTiempo");
                });
#pragma warning restore 612, 618
        }
    }
}
